name: gradutionproject
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rolling_switch: ^0.0.2
  firebase_core: ^2.18.0
  firebase_database: ^10.3.0
  cloud_firestore:
  firebase_storage: ^11.3.0
  firebase_auth: ^4.11.0
  awesome_dialog: ^3.1.0
  # alan_voice: ^3.10.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  conditional_builder_null_safety: ^0.0.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  dio: ^5.3.3
  sleek_circular_slider: ^2.0.1
  animated_splash_screen: ^1.3.0
  showcaseview: ^2.0.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: "#000000"
  # image: assets/garageoff.png

  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/logo.png"
  android: "launcher_icon"
  ios: true
# flutter pub run flutter_launcher_icons
  

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        

