// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj3B3WENmYgbzQdbbT6krbPgP-Tg2fXvo',
    appId: '1:767320576901:web:f8fab634ab6b2a8f6b6aec',
    messagingSenderId: '767320576901',
    projectId: 'graduationproject-38439',
    authDomain: 'graduationproject-38439.firebaseapp.com',
    storageBucket: 'graduationproject-38439.appspot.com',
    measurementId: 'G-QQYZX3BJW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATL8iFIvJJQyi_CEO42Y4ZlCzVoOSDC5c',
    appId: '1:767320576901:android:98e9938caf011f176b6aec',
    messagingSenderId: '767320576901',
    projectId: 'graduationproject-38439',
    storageBucket: 'graduationproject-38439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMdu5NcrcJLdmJlG-nU4Y1m89E-v_EQ0',
    appId: '1:767320576901:ios:4241a7a264f88cff6b6aec',
    messagingSenderId: '767320576901',
    projectId: 'graduationproject-38439',
    storageBucket: 'graduationproject-38439.appspot.com',
    iosBundleId: 'com.example.gradutionproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwMdu5NcrcJLdmJlG-nU4Y1m89E-v_EQ0',
    appId: '1:767320576901:ios:4241a7a264f88cff6b6aec',
    messagingSenderId: '767320576901',
    projectId: 'graduationproject-38439',
    storageBucket: 'graduationproject-38439.appspot.com',
    iosBundleId: 'com.example.gradutionproject',
  );
}
